#Numerical
x=5
price=5.2
print(type(price))
print(type(x))
num=3e6
print(num)
print(type(num))
z=4+5j
print(z)
print(type(z))
print(abs(-44))
print(pow(2,3))
print(type(pow(2,3)))
print(round(3.14))
nums=[4,2,33,4,78,9]
print(max(nums))
print(min(nums))
print(sum(nums))